### ISSUE TITLE
XMPFilesStatic Does Not Compile in Release Mode using VS Build Tools v142

### ISSUE THREAD

**Issue by amtopel** [adobe/xmp-docs#12] opened 2019-10-12 22:37 UTC
I successfully compiled the XMP libraries using Visual Studio 2015, per the instructions.  However, when I tried to use the compiled libraries in the release mode of my project in Visual Studio 2019, it said the libraries were created using an old compiler, so I needed to recompile them with a newer compiler.

So then I tried to compile the libraries in Visual Studio 2019, retargeting for the v142 toolset.  But there's a compiler error:

`C3848	expression having type 'const P2SpannedClip_Order' would lose some const-volatile qualifiers in order to call 'bool P2SpannedClip_Order::operator ()(P2_Clip *,P2_Clip *)'	XMPFilesStatic	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xtree	1685	`	

From what I can gather, the problematic code in the XMP source is in P2_Support.cpp, at line 286:

```
P2_SpannedClip::P2_SpannedClip(const std::string & p2ClipMetadataFilePath):
	P2_Clip(p2ClipMetadataFilePath)
{
	P2_Clip* p2Clip= dynamic_cast<P2_Clip*>(this);
	spannedP2Clip.insert(p2Clip);
	if (p2Clip->GetClipId())
		addedClipIds.insert(*p2Clip->GetClipId());
}
```

Please help.

**Comment by angupt** [comment] 2019-10-14 07:09
@amtopel I think, the problem is operator () of P2SpannedClip_Order should be marked const so const qualifier would not lose. Since XMP SDK is not officially available on vs2019(v142), I suggest you to make following changes in your SDK code :

File : P2_Support.hpp, Line no:82

bool operator()( P2_Clip* lhs,  P2_Clip* rhs)  **const**
{
	return lhs->GetOffsetInShot() < rhs->GetOffsetInShot();
}

I hope this will fix the compiler issue. Please let me know, if you face any other issues.

**Comment by amtopel** [comment] 2019-10-14 16:39
Thank you very much!  It compiles now.

**Comment by angupt** [comment] 2019-10-14 16:41
Closing the issue.

**Closed by angupt** 2019-10-14 16:41 UTC
